# fly.toml app configuration file generated for ai-storybook-generator on 2023-08-06T19:56:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-storybook-generator"
primary_region = "den"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
